---
- hosts: sunpower

  vars_files:
    - vars/main.yml

  remote_user: root
  tasks:
  - name: get node PPA
    get_url:
      url=https://deb.nodesource.com/setup
      dest=/tmp/setup

  - name: Add PPA
    command: /bin/bash /tmp/setup

  - name: Ensure node is latest ver
    apt: pkg=nodejs state=latest update_cache=yes
